-- MySQL Script generated by MySQL Workbench
-- 05/23/17 22:41:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sekolahku
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sekolahku
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sekolahku` DEFAULT CHARACTER SET latin1 ;
USE `sekolahku` ;

-- -----------------------------------------------------
-- Table `sekolahku`.`aset_bangunan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`aset_bangunan` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`aset_bangunan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NULL DEFAULT NULL,
  `nama_bangunan` VARCHAR(20) NULL DEFAULT NULL,
  `kode_bangunan` VARCHAR(25) NULL DEFAULT NULL,
  `register_bangunan` VARCHAR(8) NULL DEFAULT NULL,
  `kondisi_bangunan` VARCHAR(2) NULL DEFAULT NULL,
  `kostruksi_bangunan` VARCHAR(15) NULL DEFAULT NULL,
  `luas_lantai` INT(5) NULL DEFAULT NULL,
  `lokasi` VARCHAR(90) NULL DEFAULT NULL,
  `tahun_pembangunan` YEAR(4) NULL DEFAULT NULL,
  `luas_bangunan` INT(8) NULL DEFAULT NULL,
  `biaya_pembangunan` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`aset_tanah`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`aset_tanah` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`aset_tanah` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `no_persil` VARCHAR(30) NOT NULL,
  `kepemilikan` VARCHAR(20) NULL DEFAULT NULL,
  `atasnama_sertifikat` VARCHAR(60) NULL DEFAULT NULL,
  `status_tanah` VARCHAR(20) NULL DEFAULT NULL,
  `luas_tanah` INT(8) NULL DEFAULT NULL,
  `no_sertifikat` VARCHAR(100) NULL DEFAULT NULL,
  `tgl_sertifikat` DATE NULL DEFAULT NULL,
  `thn_perolehan` YEAR(4) NULL DEFAULT NULL,
  `harga_perolehan` DOUBLE NULL DEFAULT NULL,
  `asal_usul` VARCHAR(30) NULL DEFAULT NULL,
  `unit` VARCHAR(40) NULL DEFAULT NULL,
  `letak` TEXT NULL DEFAULT NULL,
  `peruntukan` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`data_guru`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`data_guru` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`data_guru` (
  `no` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `tahun_ajaran` VARCHAR(10) NULL DEFAULT NULL,
  `nbm` INT(10) NULL DEFAULT NULL,
  `nama_guru` VARCHAR(35) NULL DEFAULT NULL,
  `bidang` VARCHAR(30) NULL DEFAULT NULL,
  `nuptk` INT(25) NULL DEFAULT NULL,
  `nip` INT(30) NULL DEFAULT NULL,
  `tempat_lahir` VARCHAR(30) NULL DEFAULT NULL,
  `tgl_lahir` DATE NULL DEFAULT NULL,
  `telepon` INT(15) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `pangkat_golruang` VARCHAR(30) NULL DEFAULT NULL,
  `tgl_pengangkatan` DATE NULL DEFAULT NULL,
  `sertifikasi_guru` VARCHAR(15) NULL DEFAULT NULL,
  `tmt_sertifikasi` DATE NULL DEFAULT NULL,
  `jk` VARCHAR(4) NULL DEFAULT NULL,
  `sts_pegawai` VARCHAR(10) NULL DEFAULT NULL,
  `organisasi` VARCHAR(15) NULL DEFAULT NULL,
  `alamat` VARCHAR(20) NULL DEFAULT NULL,
  `rt_rw` INT(5) NULL DEFAULT NULL,
  `kelurahan` VARCHAR(30) NULL DEFAULT NULL,
  `kec` INT(2) NULL DEFAULT NULL,
  `kab` INT(2) NULL DEFAULT NULL,
  `prov` VARCHAR(30) NULL DEFAULT NULL,
  `pendidikan` VARCHAR(5) NULL DEFAULT NULL,
  `jurusan` VARCHAR(15) NULL DEFAULT NULL,
  `univ` VARCHAR(25) NULL DEFAULT NULL,
  `thn_lulus` YEAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`jurusan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`jurusan` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`jurusan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `nama_sekolah` VARCHAR(20) NOT NULL,
  `thn_ajaran` VARCHAR(20) NOT NULL,
  `jurusan` VARCHAR(25) NOT NULL,
  `akreditasi` VARCHAR(20) NOT NULL,
  `sk_akreditasi` VARCHAR(20) NOT NULL,
  `tglsk_akreditasi` DATE NOT NULL,
  `tgl_habis` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`kabupaten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`kabupaten` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`kabupaten` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kabupaten` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`kepsek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`kepsek` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`kepsek` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `tahun_ajaran` VARCHAR(50) NOT NULL,
  `kepala_sekolah` VARCHAR(30) NOT NULL,
  `nbm` INT(8) NOT NULL,
  `tgl_lahir` DATE NOT NULL,
  `sk_pengangkatan` INT(20) NOT NULL,
  `tgl_sk` DATE NOT NULL,
  `asal_sk` VARCHAR(30) NOT NULL,
  `tmt_jabatan` DATE NOT NULL,
  `masa_tugaske` VARCHAR(2) NOT NULL,
  `tgl_berahir` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `npsn` (`npsn` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`prestasi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`prestasi` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`prestasi` (
  `no` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `thn_ajaran` VARCHAR(10) NOT NULL,
  `jns_prestasi` VARCHAR(30) NOT NULL,
  `level` VARCHAR(30) NOT NULL,
  `hasil` VARCHAR(30) NOT NULL,
  `ket` VARCHAR(30) NOT NULL,
  `pemegang` VARCHAR(30) NOT NULL,
  `tgl_plaksanaan` DATE NOT NULL,
  PRIMARY KEY (`no`),
  UNIQUE INDEX `npsn` (`npsn` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`profil` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`profil` (
  `id` INT(11) NOT NULL,
  `jenjang` VARCHAR(30) NOT NULL,
  `npsn` INT(10) NOT NULL,
  `sk_pendirian` VARCHAR(20) NOT NULL,
  `tgl_pendirian` DATE NOT NULL,
  `alamat` VARCHAR(50) NOT NULL,
  `kel` VARCHAR(20) NOT NULL,
  `kec` INT(4) NOT NULL,
  `kab` INT(4) NOT NULL,
  `telepon` VARCHAR(15) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `web` VARCHAR(30) NOT NULL,
  `akreditasi` VARCHAR(2) NOT NULL,
  `sk_akreditasi` VARCHAR(20) NOT NULL,
  `kurikulum` VARCHAR(10) NOT NULL,
  `visi` TEXT NOT NULL,
  `misi` TEXT NOT NULL,
  `tujuan` TEXT NOT NULL,
  `moto` TEXT NOT NULL,
  `koordinat_long` DOUBLE NOT NULL,
  `koordinat_lat` DOUBLE NOT NULL,
  `listrik` INT(8) NOT NULL,
  `akses_internet` INT(8) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`sarpras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`sarpras` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`sarpras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NULL DEFAULT NULL,
  `nama_sekolah` VARCHAR(30) NULL DEFAULT NULL,
  `nama_prasarana` VARCHAR(25) NULL DEFAULT NULL,
  `jumlah` INT(8) NULL DEFAULT NULL,
  `kondisi_baik` INT(4) NULL DEFAULT NULL,
  `kondisi_rusakringan` INT(4) NULL DEFAULT NULL,
  `kondisi_rusaksedang` INT(2) NULL DEFAULT NULL,
  `kondisi_rusakberat` INT(4) NULL DEFAULT NULL,
  `kondisi_sarpras` VARCHAR(5) NULL DEFAULT NULL,
  `status_kepemilikan` VARCHAR(20) NULL DEFAULT NULL,
  `tahun_pengadaan` INT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `npsn` (`npsn` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`siswa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`siswa` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`siswa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `tahun_ajaran` VARCHAR(9) NOT NULL,
  `kelas` INT(4) NOT NULL,
  `jurusan` VARCHAR(30) NOT NULL,
  `rombel` INT(3) NOT NULL,
  `jumlah_putra` INT(3) NOT NULL,
  `jumlah_putri` INT(3) NOT NULL,
  `kms` INT(3) NOT NULL,
  `non_kms` INT(3) NOT NULL,
  `jumlah_siswa` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `npsn` (`npsn` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`tenkependik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`tenkependik` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`tenkependik` (
  `no` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `tahun_ajaran` VARCHAR(9) NOT NULL,
  `nbm` INT(10) NOT NULL,
  `jabatan` VARCHAR(15) NOT NULL,
  `nama` VARCHAR(30) NOT NULL,
  `nip` VARCHAR(20) NOT NULL,
  `tempat_lhr` VARCHAR(20) NOT NULL,
  `tgl_lhr` DATE NOT NULL,
  `telepon` INT(15) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `pangkat` VARCHAR(25) NOT NULL,
  `tgl_pengangkatan` DATE NOT NULL,
  `jk` VARCHAR(2) NOT NULL,
  `status_pegawai` VARCHAR(10) NOT NULL,
  `organisasi` VARCHAR(20) NOT NULL,
  `alamat` VARCHAR(50) NOT NULL,
  `rt_rw` INT(4) NOT NULL,
  `kel` VARCHAR(20) NOT NULL,
  `kec` VARCHAR(20) NOT NULL,
  `kab` VARCHAR(20) NOT NULL,
  `prov` INT(20) NOT NULL,
  `pnd_thr` INT(10) NOT NULL,
  PRIMARY KEY (`no`),
  UNIQUE INDEX `npsn` (`npsn` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`user` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `Nama` VARCHAR(256) NOT NULL,
  `level` TINYINT(1) NOT NULL,
  `Foto` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`wakasek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`wakasek` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`wakasek` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npsn` INT(10) NOT NULL,
  `tahun_ajaran` VARCHAR(9) NOT NULL,
  `nbm` INT(10) NOT NULL,
  `wakil_kepala` VARCHAR(30) NOT NULL,
  `waka_bidang` VARCHAR(20) NOT NULL,
  `sk_pengangkatan` VARCHAR(30) NOT NULL,
  `tgl_sk` DATE NOT NULL,
  `asal_sk` VARCHAR(10) NOT NULL,
  `tmt_jabatan` DATE NOT NULL,
  `masa_tugaske` VARCHAR(2) NOT NULL,
  `tgl_habis` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `npsn` (`npsn` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`kecamatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`kecamatan` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`kecamatan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kecamatan` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sekolahku`.`provinsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sekolahku`.`provinsi` ;

CREATE TABLE IF NOT EXISTS `sekolahku`.`provinsi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `provinsi` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
